Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,51 +1,48 @@
-name: Deploy to server
+name: Deploy CRM to APACHE
+
 on:
   push:
     branches:
       - main
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-      - name: Setup SSH With Ec2 instance
-        uses: webfactory/ssh-agent@v0.9.0
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+    - name: Set up SSH for EC2
+      uses: webfactory/ssh-agent@v0.6.0
+      with:
+        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Making git safe directory
-        run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 << 'EOF'
+    - name: Set git safe dir
+      run: |
+        ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 <<'EOF'
           git config --global --add safe.directory /var/www/html/Apache
-          EOF
+        EOF
 
-      - name: Deploy To Server
-        run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 << 'EOF'
+    - name: Deploy
+      run: |
+        ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 <<'EOF'
           set -e
-          set -x  # Enable debugging to show commands being executed
 
-          # Navigate to the project directory
-          cd /var/www/html/Apache/
-
-          # Save the current commit hash for rollback
+          # Save the current state
+          cd /var/www/html/Apache
           LAST_COMMIT=$(git rev-parse HEAD)
           echo $LAST_COMMIT > /home/ubuntu/last_commit
 
-          # Check the status of the repository and pull the latest changes
-          git status
+          # Try deploying
           git checkout main
           git pull origin main || {
-            echo "Deployment failed due to git pull error"
-            git reset --hard $(cat /home/ubuntu/last_commit)
-            exit 1
+            echo "Deployment failed, rolling back ...";
+            git reset --hard $(cat /home/ubuntu/last_commit);
+            exit 1;
           }
 
-          # Set ownership for the project directory
+          # Change ownership after deployment
           chown -R www-data:www-data /var/www/html/Apache
+        EOF
 
-          echo "Deployment successful"
-          EOF
